SistemaEscola/Controllers/AlunoController.cs
using Microsoft.AspNetCore.Mvc;
using SistemaEscola.Domain.Exceptions;
using SistemaEscola.Domain.Interfaces.Applications;
using SistemaEscola.Domain.Models;

namespace SistemaEscola.Controllers
{
    [ApiController]
    [Route("api/[controller]")]
    public class AlunoController : ControllerBase
    {
        private readonly IAlunoApplication _alunoApplication;

        public AlunoController(IAlunoApplication alunoApplication)
        {
            _alunoApplication = alunoApplication;
        }

        [HttpGet]
        public async Task<IActionResult> GetAll()
        {
            try
            {
                return Ok(await _alunoApplication.GetAll());
            }
            catch (ErrorException ex)
            {
                return BadRequest(ErrorCodeModel.Create(ex.Code, ex.Message));
            }
        }
    }
}

SistemaEscola/Pages/Aluno.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using SistemaEscola.Domain.Interfaces.Applications;

namespace SistemaEscola.Pages
{
    public class Aluno : PageModel
    {
        private readonly IAlunoApplication _alunoApplication;
        public IEnumerable<Domain.Models.Alunos.AlunoModel> Alunos { get; private set; }

        public Aluno(IAlunoApplication alunoApplication)
        {
            _alunoApplication = alunoApplication;
        }

        public async Task OnGet()
        {
            Alunos = await _alunoApplication.GetAll();
        }

        public async Task<IActionResult> OnPostInativarAsync(int id)
        {
            var hasCreated = await _alunoApplication.Delete(id);

            if (!hasCreated)
                return RedirectToPage("/ErroRequisicao");

            return RedirectToPage();
        }
    }
}

SistemaEscola/Pages/Alunos/Criar.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using SistemaEscola.Domain.Interfaces.Applications;
using SistemaEscola.Domain.Models.Alunos;

namespace SistemaEscola.Pages.Alunos
{
    public class CriarAluno : PageModel
    {
        private readonly IAlunoApplication _alunoApplication;

        public CriarAluno(IAlunoApplication alunoApplication)
        {
            _alunoApplication = alunoApplication;
        }

        public async Task<IActionResult> OnPostAsync(AlunoCreateModel aluno)
        {
            var hasCreated = await _alunoApplication.Add(aluno);

            if (!hasCreated)
                return RedirectToPage("/ErroRequisicao");

            return RedirectToPage("/Alunos/Listar");
        }
    }
}

SistemaEscola/Pages/Alunos/Listar.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using SistemaEscola.Domain.Interfaces.Applications;

namespace SistemaEscola.Pages.Alunos
{
    public class Aluno : PageModel
    {
        private readonly IAlunoApplication _alunoApplication;
        public IEnumerable<Domain.Models.Alunos.AlunoModel> Alunos { get; private set; }

        public Aluno(IAlunoApplication alunoApplication)
        {
            _alunoApplication = alunoApplication;
        }

        public async Task OnGet()
        {
            Alunos = await _alunoApplication.GetAll();
        }

        public async Task<IActionResult> OnPostInativarAsync(int id)
        {
            var hasCreated = await _alunoApplication.Delete(id);

            if (!hasCreated)
                return RedirectToPage("/ErroRequisicao");

            return RedirectToPage();
        }
    }
}

SistemaEscola/Pages/CriarAluno.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using SistemaEscola.Domain.Interfaces.Applications;
using SistemaEscola.Domain.Models.Alunos;

namespace SistemaEscola.Pages
{
    public class CriarAluno : PageModel
    {
        private readonly IAlunoApplication _alunoApplication;

        public CriarAluno(IAlunoApplication alunoApplication)
        {
            _alunoApplication = alunoApplication;
        }

        public async Task<IActionResult> OnPostAsync(AlunoCreateModel aluno)
        {
            var hasCreated = await _alunoApplication.Add(aluno);

            if (!hasCreated)
                return RedirectToPage("/ErroRequisicao");

            return RedirectToPage("/Aluno");
        }
    }
}

SistemaEscola/Pages/ErroRequisicao.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace SistemaEscola.Pages
{
    public class ErroRequisicao : PageModel
    {
        private readonly ILogger<ErroRequisicao> _logger;

        public ErroRequisicao(ILogger<ErroRequisicao> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {

        }
    }

}

SistemaEscola/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace SistemaEscola.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }

}

SistemaEscola/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace SistemaEscola.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {

        }
    }
}

SistemaEscola/Pages/Aluno.cshtml
@page
@model Aluno
@{
    ViewData["Title"] = "Alunos";
}

<style>
    .container {
        max-width: 800px;
        margin: 0 auto;
        padding: 20px;
    }

    .btn-primary {
        background-color: #007bff;
        color: #fff;
        border: none;
        padding: 10px 20px;
        border-radius: 5px;
        text-decoration: none;
    }

        .btn-primary:hover {
            background-color: #0056b3;
        }

    .table {
        width: 100%;
        border-collapse: collapse;
    }

        .table th, .table td {
            padding: 8px;
            border: 1px solid #ddd;
            text-align: left;
        }

        .table thead th {
            background-color: #343a40;
            color: #fff;
        }
</style>

<div class="container">
    <div style="margin-bottom: 20px;">
        <a class="btn btn-primary" role="button" asp-page="/CriarAluno">Novo Aluno</a>
    </div>

    <h1>Alunos</h1>

    <table class="table">
        <thead class="thead-dark">
            <tr>
                <th scope="col">#</th>
                <th scope="col">Nome</th>
                <th scope="col">Usuário</th>
                <th scope="col">Ações</th>
            </tr>
        </thead>
        <tbody>
            @if (Model != null && Model.Alunos.Any())
            {
                foreach (var aluno in Model.Alunos)
                {
                    <tr>
                        <td>@aluno.Id</td>
                        <td>@aluno.Nome</td>
                        <td>@aluno.Usuario</td>
                        <td>
                            <form method="post" asp-page-handler="Inativar" asp-route-id="@aluno.Id">
                                <button type="submit" class="btn btn-danger">Inativar</button>
                            </form>
                        </td>
                    </tr>
                }
            }
        </tbody>
    </table>
</div>

SistemaEscola/Pages/CriarAluno.cshtml
@page
@model CriarAluno
@{
    ViewData["Title"] = "AlunosCriar";
}

<style>
    .container {
        max-width: 800px;
        margin: 0 auto;
        padding: 20px;
    }

    .btn-primary {
        background-color: #007bff;
        color: #fff;
        border: none;
        padding: 10px 20px;
        border-radius: 5px;
        text-decoration: none;
    }

        .btn-primary:hover {
            background-color: #0056b3;
        }

    .form-group {
        margin-bottom: 20px;
    }
</style>

<div class="container">
    <div style="margin-bottom: 20px;">
        <a class="btn btn-primary" role="button" asp-page="/Aluno">Voltar</a>
    </div>

    <h1>Criar Aluno</h1>

    <form method="post">
        <div class="form-group">
            <label for="nome">Nome:</label>
            <input type="text" id="CriarAluno.Nome" name="nome" class="form-control" />
        </div>
        <div class="form-group">
            <label for="usuario">Usuário:</label>
            <input type="text" id="CriarAluno.Usuario" name="usuario" class="form-control" />
        </div>
        <div class="form-group">
            <label for="senha">Senha:</label>
            <input type="password" id="CriarAluno.Senha" name="senha" class="form-control" />
            <small id="senhaHelp" class="form-text text-muted">A senha deve conter pelo menos 8 caracteres, incluindo letras maiúsculas, minúsculas, números e caracteres especiais.</small>
        </div>
        <button type="submit" class="btn btn-primary" asp-page-handler="OnGet">Cadastrar</button>
    </form>
</div>

SistemaEscola/Pages/ErroRequisicao.cshtml
@page
@{
    ViewData["Title"] = "ErroRequisicao";
}

<style>
    .container {
        max-width: 800px;
        margin: 0 auto;
        padding: 20px;
    }

    .btn-primary {
        background-color: #007bff;
        color: #fff;
        border: none;
        padding: 10px 20px;
        border-radius: 5px;
        text-decoration: none;
    }

        .btn-primary:hover {
            background-color: #0056b3;
        }

    .form-group {
        margin-bottom: 20px;
    }
</style>

<div class="container">
    <div style="margin-bottom: 20px;">
        <a class="btn btn-primary" role="button" asp-page="/Alunos/Listar">Voltar</a>
    </div>

    <h1>Erro ao realizar o cadastro</h1>
        
</div>

SistemaEscola/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h1 class="display-4">SistemaEscola</h1>
    <p>Bem-vindo ao cadastro de Alunos e Turmas</p>
</div>